### ISSUE TITLE
Weird Issue on Mac (Testing on Linux)

### ISSUE THREAD

**Issue by Logalicioustuff** [garrynewman/gmad#17]
So I've been working on an addon for a while, and I've figured out how to publish it to the workshop, the only problem is the gmad creator is not working properly. So I have my folder located at "~/Desktop/omgamazingaddon/" without addon.json in it. This is what gmad prints out in the terminal:

Logans-Mac-Mini:bin Logan$ ./gmad_osx create -folder ~/Desktop/omgamazingaddon -out ~/Desktop/hi.gma
Garry's Mod Addon Creator 1.1
Looking in folder "/Users/Logan/Desktop/omgamazingaddon/"
/Users/Logan/Desktop/omgamazingaddon/addon.json error: Couldn't find file

So yeah it can't find addon.json. It's not there. Now we get to the problem... If I put addon.json in the folder, it reads it... kinda... This is what it prints out:

Logans-Mac-Mini:bin Logan$ ./gmad_osx create -folder ~/Desktop/omgamazingaddon -out ~/Desktop/hi.gma
Garry's Mod Addon Creator 1.1
Looking in folder "/Users/Logan/Desktop/omgamazingaddon/"
No files found, can't continue!
File list verification failed

That's the problem I'm having. Here is how my folder is set up.

omgamzingaddon - The root folder
omgamazingaddon/addon.json - The addon.json file.
omgamazingaddon/lua Subfolder
omgamazingaddon/sound - Subfolder
omgamazingaddon/lua/autorun -SubSubFolder
omgamazingaddon/sound/addon_music - SubSubFolder
omgamazingaddon/lua/autorun/* - My lua scripts.
omgamazingaddon/sound/addon_music/* - My addon's music

I hope I've explained enough in an understandable way (judging I'm trying to give a lot... O_o)

**Comment by whisperity** [comment]
What do you put in the `addon.json`?
It has a set layout, like:

    {
    	"title"		:	"My Test Addon",
    	"type"		:	"gamemode",
    	"tags"		:	[ "fun", "cartoon" ],
    	"ignore"	:
    	[
    		"*.psd",
    		"*.vcproj",
    		"*.svn*"
     	]
    }

The `ignore` part can be omitted, but the `type` and `tags` parts must have their values set from the following list in this file: https://github.com/garrynewman/gmad/blob/master/include/AddonFormat.h (the Type and Misc arrays).

Also, for that, try at first running the program with the `-warninvalid` flag set (that will make it only prompt on an errorneous file instead of terminating), and if that is not working, supply absolute path instead of relative ones.

So: instead of
`./gmad_osx create -folder ~/Desktop/omgamazingaddon -out ~/Desktop/hi.gma`
call the program as
`./gmad_osx create -folder "/Users/Logan/Desktop/omgamazingaddon" -out "/Users/Logan/Desktop/hi.gma" -warninvalid`.

**Comment by Logalicioustuff** [comment]
Sorry about the long delay, just got back from a long trip today. The addon.json was formatted exactly like that, so that shouldn't be an issue... The tags are type were using what was available correctly, that shouldn't be an issue later... Will post another reply with the results of the rest soon.

**Comment by whisperity** [comment]
There were errors with bootil apparently: https://github.com/garrynewman/bootil/pull/15. So this should be fixed soon, I guess.

**Comment by robotboy655** [comment]
Please test whether this is fixed in Dev branch.
http://wiki.garrysmod.com/page/Dev_Branch

**Comment by Logalicioustuff** [comment]
Will do.

**Comment by Logalicioustuff** [comment]
Aha! Seems to work! (Only have to remove .DS_Store from my directories) but looks like it will work! Will edit when it does/doesn't work.

**Comment by Bo98** [comment]
Good point about .DS_Store. I'll send a pull request for that.

**Comment by robotboy655** [comment]
You should be able to just ignore those via ignore part of addon.json.

**Comment by Bo98** [comment]
It should be ignored in GMad though because it is a hidden file that is in almost every directory.
